import React, { useState } from 'react'
import { FiMapPin } from "react-icons/fi";
import { FiPhone } from "react-icons/fi";
import { IoMailOutline } from "react-icons/io5";
import Head from 'next/head'
import  { useRef } from 'react';
import emailjs from '@emailjs/browser';
import Config from '../components/Config';



function Contact() {
  const [showModal, setShowModal] = useState(false)


    const handleClose =()=>{
      setShowModal(false)
    }

  const form = useRef();

  const sendEmail = (e) => {
    e.preventDefault();

    emailjs.sendForm('service_dfqossz', 'template_4w3f0pl', form.current, 'S4LkGEuNJEtCzceXF')
      .then((result) => {
          console.log(result.text);
      }, (error) => {
          console.log(error.text);
      });
      e.target.reset()
  };

  return (
    
    <div className='background'>
       <style jsx>{`
              .background {
                background-image: url("https://cdn.pixabay.com/photo/2016/11/22/21/57/apparel-1850804_960_720.jpg");
              }
        `}
      </style>
      <Head>
        <title>Contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='relative flex items-top justify-center min-h-screen sm:items-center sm:pt-0'>
        <div className='max-w-6xl mx-auto sm:px-6 lg:px-8'>
          <div className='mt-8 overflow-hidden'>
            <div className='grid grid-cols-1 md:grid-cols-2'>
              <div className='p-6 mr-2 bg-gray-100 dark:bg-gray-800 rounded-lg'>
                <h1 className=' text-4xl sm:text-5xl text-gray-800 dark:text-white font-extrabold tracking-tight'>Contact Us</h1>
                <p className='text-normal text-lg sm:text-2xl font-medium text-gray-600 dark:text-gray-400 mt-2'>Fill in the form to start a conversation</p>
                <div className='flex items-center mt-8 text-gray-600 dark:text-gray-400'>
                <FiMapPin className='w-8 h-8 text-gray-500' />
                <div className='ml-4 text-md tracking-wide font-semibold w-40'>Karlsruher Str.32 Baden-Wüttenberg 12345</div>
              </div>
              <div className='flex items-center mt-4 text-gray-600 dark:text-gray-400'>
                <FiPhone className='w-8 h-8 text-gray-500'/>
                <div className='ml-4 text-md tracking-wide font-semibold w-40'>+49123456789</div>
              </div>
              <div className='flex items-center mt-2 text-gray-600 dark:text-gray-400'>
                <IoMailOutline className='w-8 h-8 text-gray-500'/>
                <div className='ml-4 text-md tracking-wide font-semibold w-40'>amir@gmail.com</div>
              </div>
              </div>

              <form className='p-6 flex flex-col justify-center' ref={form} onSubmit={sendEmail}>
                <div className='flex flex-col'>
                  <label className='hidden'>Full Name</label>
                  <input placeholder='Full Name' className='w-100 mt-2 py-3 px-3 rounded-lg bg-white  border border-gray-400 dark:border-gray-700 text-gray-800 font-semibold  focus:outline-none' name='name' />
                </div>
                <div className='flex flex-col'>
                  <label className='hidden'>Email</label>
                  <input placeholder='Email' className='w-100 mt-2 py-3 px-3 rounded-lg bg-white  border border-gray-400 dark:border-gray-700 text-gray-800 font-semibold  focus:outline-none' type="email" name="email" required />
                </div>
                <div className='flex flex-col'>
                  <label className='hidden'>your text </label>
                  <textarea placeholder='your text...' className='w-100 mt-2 py-3 px-3 rounded-lg bg-white  border border-gray-400 dark:border-gray-700 text-gray-800 font-semibold  focus:outline-none' name='message' />
                </div>
                <button className='md:w-32 bg-blue-600 hover:bg-blue-dark text-white font-bold py-3 rounded-lg mt-3 hover:bg-blue-700 transition ease-out duration-300' value="send" onClick={()=>setShowModal(true)}>submit</button>
              </form>
              {showModal && <Config handleClose={handleClose} >
                <h1>vielen Dnak</h1>
                <p>Email wurde gesendet</p>
                </Config>}
               
             
          </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Contact
