import Head from 'next/head'
import SlideShow from '../components/SlideShow'



export default function Home() {

  
  return (
    <div>
      <Head>
        <title>Amirrroff | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
        <SlideShow />
        </div>
    </div>
    </div>
  )
}
