
import Head from 'next/head'
import Link from 'next/link'
import InputEmail from '../containers/InputEmail/InputEmail';
import InputPassword from '../containers/InputPassword/InputPassword';
import Button from '../containers/Button/Button';
import { useDispatch } from 'react-redux'
import actionTypes from '../configs/actionTypes';
import { useState } from 'react';



const Login = () => {

    const dispatch = useDispatch()
    const [form, setForm] = useState({})


    const handleSubmit = (event) =>{
      if(event) event.preventDefault()
      console.log(form)
      dispatch({
        type:actionTypes.LOGIN,
        logged: true,
        email:form.email
      })
    }

    const handleOnChange = (name, value)=>{
      setForm({
        ...form,
        [name]: value
      })
    }
    return ( 
        <div className='background'>
          <style jsx>{`
              .background {
                background-image: url("https://cdn.pixabay.com/photo/2016/11/22/21/57/apparel-1850804_960_720.jpg");
              }
        `}
      </style>
            <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <form className='py-36 min-h-screen' onSubmit={handleSubmit}>
        <div className="bg-gray-200 rounded-md p-2 mx-auto w-8/12 h-8/12  ">
            <div className="text-left ml-8">
                <h2 className="pb-2 text-center font-bold text-2xl">LOGIN</h2>
                
                <hr className="border-2 border-gray-400 mb-4" />
                <label className="font-bold ">Email</label>
                <br className='mb-2' />
                    <InputEmail placeholder="Email adresse" onChange={(value)=>handleOnChange("email", value)} required />
                    <br />
                    <label className="font-bold mb-2">Password</label>
                    <br className='mb-2' />
                    <InputPassword placeholder="Password" onChange={(value)=>handleOnChange("password", value)} required/>
                    <br />
                    <Button type='submit'>Login</Button>
                    <br />
                    <Link href="/Register"><a className='text-blue-400 hover:text-blue-700'>Register</a></Link>
            </div>
            </div>
            </form>
      </div>
        </div>
     );
}
 
export default Login;