import { BiHeart } from "react-icons/bi";
import Head from 'next/head'


export const getStaticProps = async()=>{
    const res = await fetch('https://fakestoreapi.com/products')
    const data =await res.json()
  
    return{
      props:{ ninjas: data}
    }
  }
  
  
  const Shop = ({ ninjas }) => {
    return ( 
      <div className='background'>
       <style jsx>{`
              .background {
                background-image: url("https://cdn.pixabay.com/photo/2016/11/22/21/57/apparel-1850804_960_720.jpg");
              }
        `}
      </style>
         <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <ul className="flex flex-wrap sm:p-10 ml-16">
       {ninjas.map(item => (
         <div key={item.id}> 
             <li className="w-80 h-5/6 m-4 border rounded-lg p-20 shadow-lg bg-zinc-100">
               <div>
               
                 <div className="mt-4 text-center">
                   <h1 className="font-bold w-32 h-18">{item.title}</h1>
                   <span className="block">
                      <p className="w-18 h-10 mt-8"> Price : {item.price}€</p>
                   </span>
                </div>
                </div>
                <div className="flex flex-wrap m-2 p-1">
                    <button className='border w-56 py-2 bg-black text-white '>BUY NOW</button>
                    <button className='border w-48 py-2  '>ADD TO BAG </button>
                    <button className='border py-3 p-2'><BiHeart /></button>
                </div>
             </li>
           </div>
       ))}
          </ul>

      </div>
     );
  }
   
  export default Shop;